# Generated by Django 5.1.1 on 2024-10-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
